# Generated by Django 5.0.7 on 2024-07-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.CharField(blank=True, max_length=200)),
                ('webSite', models.CharField(blank=True, max_length=200)),
                ('blockScan', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Blockchain',
                'verbose_name_plural': 'Blockchains',
                'db_table': 'blockchains',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('webSite', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
                'db_table': 'coins',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.CharField(blank=True, max_length=200)),
                ('webSite', models.CharField(blank=True, max_length=200)),
                ('type', models.SmallIntegerField(default=1)),
                ('blockchain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_cryptos.blockchain')),
                ('coin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_cryptos.coin')),
            ],
            options={
                'verbose_name': 'Staking',
                'verbose_name_plural': 'Stakings',
                'db_table': 'stakings',
                'ordering': ['id'],
            },
        ),
    ]
