# Generated by Django 5.0.7 on 2024-07-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('staking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_cryptos.stanking')),
            ],
            options={
                'verbose_name': 'StakingDetail',
                'verbose_name_plural': 'StakingDetails',
                'db_table': 'stakingDetails',
                'ordering': ['id'],
            },
        ),
    ]
