# Generated by Django 5.0.7 on 2024-07-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
