# Generated by Django 5.0.7 on 2024-07-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0002_coin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='webSite',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
