# Generated by Django 5.0.7 on 2024-07-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0002_stakingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakingdetail',
            name='quantity_earn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stanking',
            name='minimun_earn',
            field=models.FloatField(default=0),
        ),
    ]
