# Generated by Django 5.0.7 on 2024-08-01 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0003_stakingdetail_quantity_earn_stanking_minimun_earn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakingdetail',
            name='staking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='admin_cryptos.stanking'),
        ),
    ]
