# Generated by Django 5.0.7 on 2024-07-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0003_coin_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('webSite', models.CharField(blank=True, max_length=200)),
                ('blockScan', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
