# Generated by Django 5.0.7 on 2024-08-03 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0004_alter_stakingdetail_staking'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakingdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
