# Generated by Django 5.0.7 on 2024-07-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0004_blockchain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchain',
            options={'ordering': ['id'], 'verbose_name': 'Blockchain', 'verbose_name_plural': 'Blockchains'},
        ),
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['id'], 'verbose_name': 'Coin', 'verbose_name_plural': 'Coins'},
        ),
        migrations.AlterModelTable(
            name='blockchain',
            table='blockchains',
        ),
        migrations.AlterModelTable(
            name='coin',
            table='coins',
        ),
    ]
