# Generated by Django 5.0.7 on 2024-07-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0005_alter_blockchain_options_alter_coin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
