# Generated by Django 5.0.7 on 2024-07-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cryptos', '0007_alter_blockchain_description_stanking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stanking',
            options={'ordering': ['id'], 'verbose_name': 'Staking', 'verbose_name_plural': 'Stakings'},
        ),
        migrations.RemoveField(
            model_name='stanking',
            name='Blockchain',
        ),
        migrations.AddField(
            model_name='stanking',
            name='type',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='stanking',
            table='stakings',
        ),
        migrations.CreateModel(
            name='StakingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('staking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_cryptos.stanking')),
            ],
            options={
                'verbose_name': 'StakingDetail',
                'verbose_name_plural': 'StakingDetails',
                'db_table': 'stakingDetails',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='stanking',
            name='blockchain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_cryptos.blockchain'),
        ),
    ]
